# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 940568718c4c11fb3726e6db7ed12d698eddf07dc5fc1ec63c5606f26c729d0616f7d2f45360461da71b25a3c4a690fdd5621e073141222414e6fde92edc1bea

test:
  secret_key_base: 5ce6d3f91d33f4cd0c5f4092539f8f70ed36f6bae9bd258fcadf92016ed10e824226ae176b656758b528d0fa81520c35108936726a83f0de5025175dbe20e615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
